1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [119]:
import numpy as np 

m = np.arange(12).reshape((3,4))
print(m)
row = m.mean(axis=1)
col = m.mean(axis=0)

print('\nMean along the rows:', row)
print('\nMean along the columns:', col)
print('\ntotal mean of whole matrix:', np.mean(m))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Mean along the rows: [1.5 5.5 9.5]

Mean along the columns: [4. 5. 6. 7.]

total mean of whole matrix: 5.5


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [117]:
import numpy as np 

u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

print('Using the function outer in numpy:\n',np.outer(u, v, out = None))

m = np.array([(i*j) for i in u for j in v]).reshape(4,4)
print('\nUsing a nested for loop or a list comprehension:\n', m)

b = v*u.reshape(4,1)
print('\nUsing numpy broadcasting operations:\n', b)
        

Using the function outer in numpy:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Using a nested for loop or a list comprehension:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Using numpy broadcasting operations:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [121]:
import numpy as np 
m = np.arange(0, 6, 0.1).reshape(6, 10)
print('Regular matrix:\n', m)

for i in range(6):
    for j in range(10):
        if i == 0 :
            if m[i][j] % (i+1) < 0.4:
                m[i][j]=0
        elif m[i][j] %i < 0.4:
                m[i][j]=0
        
print('\n Modified matrix:\n', m)


Regular matrix:
 [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]

 Modified matrix:
 [[0.  0.  0.  0.  0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.  0.  0.  1.4 1.5 1.6 1.7 1.8 1.9]
 [0.  0.  0.  0.  2.4 2.5 2.6 2.7 2.8 2.9]
 [0.  0.  0.  0.  3.4 3.5 3.6 3.7 3.8 3.9]
 [0.  0.  0.  0.  4.4 4.5 4.6 4.7 4.8 4.9]
 [0.  0.  0.  0.  5.4 5.5 5.6 5.7 5.8 5.9]]


4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [122]:
import numpy as np 
m = np.linspace(0, 6.28, 100).astype(float)

n = m[0:100:10]
a = m[100:0:-1]
b = m[100:0:-10]
print('Original array:\n', m)
print('\nEvery 10th element:\n', n)
print('\nReversed original array:\n', a)
print('\nReversed modified array:\n', b)

mask = (abs(np.sin(a) - np.cos(a)) < 0.1)
a1 = a[mask]
print('\nElements where the absolute difference between the sin and cos functions evaluated for that element is < 0.1:', a1)

Original array:
 [0.         0.06343434 0.12686869 0.19030303 0.25373737 0.31717172
 0.38060606 0.4440404  0.50747475 0.57090909 0.63434343 0.69777778
 0.76121212 0.82464646 0.88808081 0.95151515 1.01494949 1.07838384
 1.14181818 1.20525253 1.26868687 1.33212121 1.39555556 1.4589899
 1.52242424 1.58585859 1.64929293 1.71272727 1.77616162 1.83959596
 1.9030303  1.96646465 2.02989899 2.09333333 2.15676768 2.22020202
 2.28363636 2.34707071 2.41050505 2.47393939 2.53737374 2.60080808
 2.66424242 2.72767677 2.79111111 2.85454545 2.9179798  2.98141414
 3.04484848 3.10828283 3.17171717 3.23515152 3.29858586 3.3620202
 3.42545455 3.48888889 3.55232323 3.61575758 3.67919192 3.74262626
 3.80606061 3.86949495 3.93292929 3.99636364 4.05979798 4.12323232
 4.18666667 4.25010101 4.31353535 4.3769697  4.44040404 4.50383838
 4.56727273 4.63070707 4.69414141 4.75757576 4.8210101  4.88444444
 4.94787879 5.01131313 5.07474747 5.13818182 5.20161616 5.26505051
 5.32848485 5.39191919 5.45535354 5.51878788 5.

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [114]:
import numpy as np 
m = np.arange(1, 11)
a = np.outer(m, m, out = None)
print(a)

b = np.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
print('\nThe trace of the matrix:',b)

n = np.fliplr(a).diagonal()
print('\nThe anti-diagonal matrix:\n',n)

e = np.diagonal(a, offset=1, axis1=0, axis2=1)
print('\nThe diagonal with offset by 1 upwards:\n',e)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

The trace of the matrix: 385

The anti-diagonal matrix:
 [10 18 24 28 30 30 28 24 18 10]

The diagonal with offset by 1 upwards:
 [ 2  6 12 20 30 42 56 72 90]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [124]:
import numpy as np

m = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
m = np.abs(m - m[:, np.newaxis])
n = m * 1.60934

print("2D grid of distances among each city along Route 66:\n", m, '\n\n')
print("2D grid of distances among each city along Route 66 converted in km:\n\n", n)

2D grid of distances among each city along Route 66:
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]] 


2D grid of distances among each city along Route 66 converted in km:

 [[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [116]:
import numpy as np

def prime_nums():
    nums = np.arange(100)
    mask = np.ones(nums.shape[0], dtype=bool)
    mask[0] = False
    mask[1] = False

    for i in range(2, mask.shape[0]):
        if mask[i]:
            mask[i+i::i] = False      
    return nums[mask]

print(prime_nums())

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
