1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))

In [2]:
import numpy as np

In [3]:
m = np.arange(12).reshape((3,4))
print('matrix m =','\n',m,'\n')
tot_mean = np.mean(m) 
#to find mean of each column and each row we use parameter axis, which is axis=0 for column and axis=1 for row
print('total mean =','\n',tot_mean,'\n')
col_mean = np.mean(m, axis=(0)) 
print('mean columns =','\n',col_mean,'\n')
row_mean = np.mean(m, axis=(1))
print('mean rows =','\n',row_mean,'\n')

matrix m = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

total mean = 
 5.5 

mean columns = 
 [4. 5. 6. 7.] 

mean rows = 
 [1.5 5.5 9.5] 



2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [4]:
#finding the outer product of vectors
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print('Vector_u=','\n',u,'\n')
print('Vector_v=','\n',v,'\n')

#1. using the function outer in numpy
q = np.outer(u,v)
print('Outer product using outer function in numpy =','\n',q,'\n')

#2. using nested for loop or a list comprehension
#belum kelar bikin ke matriks!!!
M =[]
for x in u:
    row = []
    for y in v:
        row.append(x * y)
    M.append(row)
print('Outer product with nested for loop=','\n',np.matrix(M))

#3. using numpy broadcasting operation
x = np.zeros((len(u),len(v)),dtype =int)
for i in range(len(v)):
    x[i] = v[i] * u
print('Outer product using numpy broadcasting operation=\n',x)

Vector_u= 
 [1 3 5 7] 

Vector_v= 
 [2 4 6 8] 

Outer product using outer function in numpy = 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

Outer product with nested for loop= 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
Outer product using numpy broadcasting operation=
 [[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [6]:
#1. Create matrix 10 by 6 using arange and reshape numpy
m = np.arange(0,6,0.1).reshape(10,6)
print('Matrix 10 by 6 = \n', m)
#2. Setting all entries with a decimal part <0.4 to zero
mask = (m%1 <0.4)
m[mask] = 0 
print('\n Matrix with set up decimal part<0.4 to zero = \n',m)




Matrix 10 by 6 = 
 [[0.  0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1.  1.1]
 [1.2 1.3 1.4 1.5 1.6 1.7]
 [1.8 1.9 2.  2.1 2.2 2.3]
 [2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5]
 [3.6 3.7 3.8 3.9 4.  4.1]
 [4.2 4.3 4.4 4.5 4.6 4.7]
 [4.8 4.9 5.  5.1 5.2 5.3]
 [5.4 5.5 5.6 5.7 5.8 5.9]]

 Matrix with set up decimal part<0.4 to zero = 
 [[0.  0.  0.  0.  0.4 0.5]
 [0.6 0.7 0.8 0.9 0.  0. ]
 [0.  0.  1.4 1.5 1.6 1.7]
 [1.8 1.9 0.  0.  0.  0. ]
 [2.4 2.5 2.6 2.7 2.8 2.9]
 [0.  0.  0.  0.  3.4 3.5]
 [3.6 3.7 3.8 3.9 0.  0. ]
 [0.  0.  4.4 4.5 4.6 4.7]
 [4.8 4.9 0.  0.  0.  0. ]
 [5.4 5.5 5.6 5.7 5.8 5.9]]


4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [7]:
import math
#creating array
n = np.linspace(0, (2*math.pi),100)
print ('Array n = \n',n,'\n' )

#extracting every 10th element with slice notation
print('Sliced array= \n', n[::10])

#reversing array with slice notation

print ('\n Reversed array= \n', n[::-10])


Array n = 
 [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [8]:
#Multiplication table
def mult_table(n):
    range = np.arange(1, n+1)
    return range*range[:, None]

p =mult_table(10)
print('Multiplication table = \n', p,'\n')

#Finding the trace of the matrix
print('Trace of the matrix =\n', p.trace(),'\n')

#finding anti diagonal of the matrix using fliplr method
print('Anti diagonal of the matrix = \n', np.fliplr(p).diagonal(),'\n')

#Extracting diagonal 1 upwards
print('Diagonal offset by 1 upwards = \n',p.diagonal(1))


Multiplication table = 
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] 

Trace of the matrix =
 385 

Anti diagonal of the matrix = 
 [10 18 24 28 30 30 28 24 18 10] 

Diagonal offset by 1 upwards = 
 [ 2  6 12 20 30 42 56 72 90]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [9]:
import pandas as pd

cities = ["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"]
#d as distance
d = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2488])
n = len(d)
print('Length of arry = \n', n, '\n')
distance = np.tile(d,n) #make 
print('Repetition as n dim = \n', distance, '\n')
#now reshape to 10*10
distance = distance.reshape(n,n)
#calculate the distance
#print broadcast
distance = np.abs(distance - distance.T)
print('Distance of each city (mil) = \n', distance, '\n')
#convert to km with broadcast, conversion factor = 1.6 approximately 1 mil = 1.609 km
dist_km = np.round(distance * 1.609)
print ('Distance in km = \n', dist_km)
df = pd.DataFrame(dist_km, index=cities) 
df.head() 
print(df)

Length of arry = 
 10 

Repetition as n dim = 
 [   0  198  303  736  871 1175 1475 1544 1913 2488    0  198  303  736
  871 1175 1475 1544 1913 2488    0  198  303  736  871 1175 1475 1544
 1913 2488    0  198  303  736  871 1175 1475 1544 1913 2488    0  198
  303  736  871 1175 1475 1544 1913 2488    0  198  303  736  871 1175
 1475 1544 1913 2488    0  198  303  736  871 1175 1475 1544 1913 2488
    0  198  303  736  871 1175 1475 1544 1913 2488    0  198  303  736
  871 1175 1475 1544 1913 2488    0  198  303  736  871 1175 1475 1544
 1913 2488] 

Distance of each city (mil) = 
 [[   0  198  303  736  871 1175 1475 1544 1913 2488]
 [ 198    0  105  538  673  977 1277 1346 1715 2290]
 [ 303  105    0  433  568  872 1172 1241 1610 2185]
 [ 736  538  433    0  135  439  739  808 1177 1752]
 [ 871  673  568  135    0  304  604  673 1042 1617]
 [1175  977  872  439  304    0  300  369  738 1313]
 [1475 1277 1172  739  604  300    0   69  438 1013]
 [1544 1346 1241  808  673  369   69  

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [27]:
import timeit
import matplotlib as plt
N = [99, 999, 9999, 4999]
t = []
l = []
for n in N:
    start = timeit.default_timer()
    for numb in range(n) :
        if numb == 1:
            pass
        if numb == 2:
            pass
        else:
            for i in range (2,numb):
                if numb%i == 0:
                    break
                elif i == numb - 1:
                    pass
                
            t.append(timeit.default_timer() - start)
    
print(t)

[1.1800000038419967e-05, 1.730000008137722e-05, 3.349999997226405e-05, 3.7199999951553764e-05, 4.250000006322807e-05, 4.579999995257822e-05, 5.220000002736924e-05, 5.51000000541535e-05, 5.880000003344321e-05, 6.200000007083872e-05, 7.100000016180275e-05, 7.380000010925869e-05, 8.390000016333943e-05, 8.679999996275001e-05, 9.049999994203972e-05, 9.330000011686934e-05, 0.00010629999997036066, 0.00010969999993903912, 0.00012409999999363208, 0.00012700000002041634, 0.00013060000014775142, 0.000133499999947162, 0.00015030000008664501, 0.0001532999999653839, 0.00015830000006644696, 0.0001611000000139029, 0.0001653000001624605, 0.00016819999996187107, 0.00018939999995382095, 0.0001922999999806052, 0.00021510000010493968, 0.00021809999998367857, 0.00022170000011101365, 0.0002246000001377979, 0.0002297000000908156, 0.00023260000011759985, 0.0002601999999569671, 0.00026309999998375133, 0.0002667000001110864, 0.00026960000013787067, 0.0002988999999615771, 0.0003017999999883614, 0.0003322000000025

In [28]:
import timeit
N1 = [99, 999, 9999, 4999]
t1 = []

non_prime = []
prime = []

for n in N1:
    start = timeit.default_timer()
    for i in range(2, n):
        if i in non_prime:
            pass
        else:
            for j in range(n):
                if i*j > n:
                    break
        
    t1.append(timeit.default_timer() - start)

print(t1)

[0.0004245000000082655, 0.005842300000040268, 0.10921690000009221, 0.03678370000011455]
