1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [ ]:
# ex04 - 1

import numpy as np
m = np.arange(12).reshape((3,4))

print("total mean is:", np.mean(m))

row_mean = np.mean(m, axis = 1)
column_mean = np.mean(m, axis = 0)

print("mean of row 1 is:", row_means[0])
print("mean of row 2 is:", row_means[1])
print("mean of row 3 is:", row_means[2])

print("mean of column 1 is:", column_means[0])
print("mean of column 2 is:", column_means[1])
print("mean of column 3 is:", column_means[2])
print("mean of column 4 is:", column_means[3])

2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [ ]:
# ex04 - 2

import numpy as np
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

# 1.
x = np.outer(u, v)
print(x)

# 2.
c = []
for row in u:
    for column in v:
        b = (row * column)
        c.append(b)
arr = np.array(c).reshape(4, 4)
print(arr)

# 3.
b = np.ones((4, 1), dtype='int8')
b[:, 0] = u
a = np.ones((4, 4), dtype='int8')
a = a * v
outer = a * b
print(outer)

3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [ ]:
# 04ex - 3

import numpy as np
m = np.arange(0, 6, 0.1).reshape(10, 6)
print(m)

4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [14]:
# 04ex - 4

import numpy as np
from math import pi
m = np.linspace(0, 2*pi, 100)
print(m)
print("\n")
n = m[::10]  # part 1
print(n)
print("\n")
r = m[::-1]  # part 2
print(r)
print("\n")
o = list([m[x] for x in range(99) if(abs(np.sin(m[x]) - np.cos(m[x]))<0.1)])  # part 3
print(o)
print("\n")
import matplotlib.pyplot as mp  # optional part
x = np.linspace(0, pi, 100)
y = np.sin(x) - np.cos(x)
mp.plot(x, y)
mp.grid()
mp.show()

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [1]:
# 04ex - 5

import numpy as np

def table(n):
    x = np.arange(1, n+1)
    return x * x[:, None]

matrx = table(10)
print("here is the matrix that shows the 10 by 10 multiplication table:\n", (matrx))
print("\n")
print("the trace of the matrix is: ", np.trace(matrx))
print("\n")
print("the anti-diagonal of the matrix is:\n", np.fliplr(matrx).diagonal())
print("\n")
print("and finally the diagonal offset by 1 upwards is:\n", np.diagonal(matrx, offset=1))

here is the matrix that shows the 10 by 10 multiplication table:
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


the trace of the matrix is:  385


the anti-diagonal of the matrix is:
 [10 18 24 28 30 30 28 24 18 10]


and finally the diagonal offset by 1 upwards is:
 [ 2  6 12 20 30 42 56 72 90]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [8]:
import numpy as np

c = np.ones((10, 2), dtype='|S20')
distance = np.array([0, 198, 303, 736, 871, 11, 1475, 1544, 1913, 2448])
city = np.array(["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"])

c[:, 1] = distance
c[:, 0] = city
print(c)
print("\n")
distance = distance * 1.6   # converting mile to km
c[:, 1] = distance
print(c)

[[b'Chicago' b'0']
 [b'Springfield' b'198']
 [b'Saint-Louis' b'303']
 [b'Tulsa' b'736']
 [b'Oklahoma City' b'871']
 [b'Amarillo' b'11']
 [b'Santa Fe' b'1475']
 [b'Albuquerque' b'1544']
 [b'Flagstaff' b'1913']
 [b'Los Angeles' b'2448']]


[[b'Chicago' b'0.0']
 [b'Springfield' b'316.8']
 [b'Saint-Louis' b'484.8']
 [b'Tulsa' b'1177.6000000000001']
 [b'Oklahoma City' b'1393.6000000000001']
 [b'Amarillo' b'17.6']
 [b'Santa Fe' b'2360.0']
 [b'Albuquerque' b'2470.4']
 [b'Flagstaff' b'3060.8']
 [b'Los Angeles' b'3916.8']]


7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)